name: "interop-public-catalog-updater"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/interop-public-catalog-updater-dev"

configmap:
  CDN_ID: "E2V4OXZKWZ5U4B"
  CDN_INVALIDATION_PATH: "/it/catalogo/*, /en/catalog/*"

cronjob:
  schedule: "0 8-20 * * 1-5"
  timeZone: "Europe/Rome"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  restartPolicy: OnFailure

  flywayInitContainer:
    create: true
    version: "11.4.0"
    downloadRedshiftDriver: false
    migrationsConfigmap: "flyway-public-catalog"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "dev"
      FLYWAY_URL: jdbc:postgresql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
      FLYWAY_SCHEMAS: "{{.Values.local.env}}_catalog" # Necessary to define the schema in which Flyway will create the flyway_schema_history table
    envFromConfigmaps:
      DB_HOST: "common-public-catalog-data.DB_HOST"
      DB_PORT: "common-public-catalog-data.DB_PORT"
      DB_NAME: "common-public-catalog-data.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "public-catalog-data-flyway-user.username"
      FLYWAY_PASSWORD: "public-catalog-data-flyway-user.password"

  env:
    BATCH_SIZE: 500
  envFromConfigmaps:
    READMODEL_SQL_DB_HOST: "common-read-model.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-public-catalog-data.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-public-catalog-data.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-public-catalog-data.DB_SCHEMA_TENANT"
    PUBLICMODEL_SQL_DB_HOST: "common-public-catalog-data.DB_HOST"
    PUBLICMODEL_SQL_DB_PORT: "common-public-catalog-data.DB_PORT"
    PUBLICMODEL_SQL_DB_NAME: "common-public-catalog-data.DB_NAME"
    PUBLICMODEL_SQL_DB_USE_SSL: "common-public-catalog-data.DB_USE_SSL"
    PUBLICMODEL_SQL_DB_SCHEMA_CATALOG: "common-public-catalog-data.DB_SCHEMA_CATALOG"
    PUBLICMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-public-catalog-data.DB_SCHEMA_ATTRIBUTE"
    PUBLICMODEL_SQL_DB_SCHEMA_TENANT: "common-public-catalog-data.DB_SCHEMA_TENANT"
  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-public-catalog-updater-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-public-catalog-updater-user.password"
    PUBLICMODEL_SQL_DB_USERNAME: "public-catalog-data-public-catalog-updater-user.username"
    PUBLICMODEL_SQL_DB_PASSWORD: "public-catalog-data-public-catalog-updater-user.password"
